// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Deque from "../src/deque.bs.js";

function of_deque(deq) {
  var match = Deque.uncons(deq);
  if (match !== undefined) {
    return {
            left: Deque.empty,
            focus: match[0],
            right: match[1]
          };
  }
  
}

function focus(t) {
  return t.focus;
}

function go_right(t) {
  var match = Deque.uncons(t.right);
  if (match !== undefined) {
    return {
            left: Deque.snoc(t.left, t.focus),
            focus: match[0],
            right: match[1]
          };
  }
  
}

function go_left(t) {
  var match = Deque.unsnoc(t.left);
  if (match !== undefined) {
    return {
            left: match[0],
            focus: match[1],
            right: Deque.cons(t.focus, t.right)
          };
  }
  
}

function to_deque(t) {
  return Curry._2(Deque.$at, t.left, Deque.cons(t.focus, t.right));
}

export {
  of_deque ,
  to_deque ,
  go_left ,
  go_right ,
  focus ,
  
}
/* Deque Not a pure module */
